### ISSUE TITLE
Make licensing clear in package+website

### ISSUE THREAD

**Issue by skyronic** [RazorFlow/framework#15]
The package currently reflects the old contents, which need to be replaced and changed. 

* Clarify that everything is free and available at no cost
* The package contents need to be updated
* Repo needs a license.md
* Website needs clarification

**Comment by aaronfranco** [comment]
Great project! However, without clear licensing it is nearly impossible to make a decision on whether or not to use it.

Do you know which license you will use? Do you have a timeframe for when this task may be completed?

**Comment by xtfer** [comment]
+1

Even if all you do is drop your choice of licence file into the root of the project, that would effectively resolve this.

**Comment by newcron** [comment]
+1

licensing is extremely unclear to me too. Esp. when looking at razorflow.com where it says "open source" but on the download page it says "download trial". the license included in that download is also not an open source license.

**Comment by skyronic** [comment]
Hi Guys,

I'm the original developer. It's quite clear this is a simple task which is long overdue. I will be spending some time this weekend improving licensing and even giving people build instructions and information how to contribute and fix minor bugs, etc.

I apologize for the big delay. I have a new job now which keeps me quite busy, and have moved to a new city. But will definitely get to this in the weekend.

**Comment by xtfer** [comment]
Thanks @skyronic.

**Comment by tarsisazevedo** [comment]
+1

**Comment by aaronfranco** [comment]
How about MIT?

**Comment by jtraulle** [comment]
@skyronic any progress on that side ?

MIT would be great :star2:

**Comment by nachomezzadra** [comment]
+1 MIT

**Comment by ChristianEnchelmaier** [comment]
I am still confused about the current licencing / pricing situation.
Can you please clearify?

**Comment by pabloorellana** [comment]
you have a great product but the licensing situation is REALLY annoying, we as developers cannot use it anymore until this is clarified, in fact I had to choose another crappy library, come on guys... don't let this stuff kill your project...

**Comment by ChristianEnchelmaier** [comment]
+1
Am 11.11.2015 9:29 nachm. schrieb "pabloorellana" <notifications@github.com

**Comment by jtraulle** [comment]
@skyronic Is RazorFlow abandonned ? No original commit from you since April ...

**Comment by murphp** [comment]
We are interested in using this and helping with the development. Any update on the licensing issue.

**Comment by murphp** [comment]
Looks like it is licensed under creative commons. Which means there is little point in anyone taking on the development of it. Surely better to change the licensing (to MIT) than leave it as a dead project?

**Comment by skyronic** [comment]
Hi Everyone,

I'm sorry for the extended delay. There is now a license file in the repository committed in 15c7a85b and as the original author, I'm clarifying that it is now officially under MIT/X11 License.

Please email me on skyronic@gmail.com or if you have any questions.

Thanks,
Anirudh
